# Site
repository: jakub-k-slys/jakub
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jakub Slys
title: Senior Principal Software Engineer
email: jakub@slys.dev
website: iam.slys.dev
phone: +48 606 462 xxx

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: jakub-k-slys
#github_username:  jakub-k-slys
#instagram_username: jakub.k.slys
linkedin_username: jakub-k-slys

# Additional icon links
additional_links:
- title: iam.slys.dev
  icon: fas fa-globe
  url: iam.slys.dev

# About Section
about_title: About
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  A highly skilled software engineer with extensive experience in high-performance systems and big data. 
  Expertise includes programming languages such as <mark>C++</mark>, <mark>JAVA</mark>, and <mark>Python</mark>. 
  
  A strong emphasis is placed on clean and maintainable code, leveraging <mark>Test-Driven Development</mark>, <mark>Behavior-Driven Development</mark>, and <mark>Domain-Driven Design</mark> to create robust and scalable solutions. 
  Work involves designing and implementing systems capable of processing large-scale data and delivering exceptional performance under heavy loads.  

  Dedicated to continuous learning and the exploration of new tools and methodologies to push the boundaries of software engineering.

  ![C](https://img.shields.io/badge/c-%2300599C.svg?style=plastic&logo=c&logoColor=white)
  ![C++](https://img.shields.io/badge/c++-%2300599C.svg?style=plastic&logo=c%2B%2B&logoColor=white)
  ![Java](https://img.shields.io/badge/java-%23ED8B00.svg?style=plastic&logo=openjdk&logoColor=white)
  ![Python](https://img.shields.io/badge/python-3670A0?style=plastic&logo=python&logoColor=ffdd54)
  ![TypeScript](https://img.shields.io/badge/typescript-%23007ACC.svg?style=plastic&logo=typescript&logoColor=white)
  ![CMake](https://img.shields.io/badge/CMake-%23008FBA.svg?style=plastic&logo=cmake&logoColor=white)
  ![Docker](https://img.shields.io/badge/docker-%230db7ed.svg?style=plastic&logo=docker&logoColor=white)
  ![Gradle](https://img.shields.io/badge/Gradle-02303A.svg?style=plastic&logo=Gradle&logoColor=white)
  ![Grafana](https://img.shields.io/badge/grafana-%23F46800.svg?style=plastic&logo=grafana&logoColor=white)
  ![Prometheus](https://img.shields.io/badge/Prometheus-E6522C?style=plastic&logo=Prometheus&logoColor=white)
  ![Kubernetes](https://img.shields.io/badge/kubernetes-%23326ce5.svg?style=plastic&logo=kubernetes&logoColor=white)
  ![ApacheCassandra](https://img.shields.io/badge/cassandra-%231287B1.svg?style=plastic&logo=apache-cassandra&logoColor=white)
  ![MySQL](https://img.shields.io/badge/mysql-4479A1.svg?style=plastic&logo=mysql&logoColor=white)
  ![Postgres](https://img.shields.io/badge/postgres-%23316192.svg?style=plastic&logo=postgresql&logoColor=white)
  ![Apache Kafka](https://img.shields.io/badge/Apache%20Kafka-000?style=plastic&logo=apachekafka)
  ![FastAPI](https://img.shields.io/badge/FastAPI-005571?style=plastic&logo=fastapi)
  ![Next JS](https://img.shields.io/badge/Next-black?style=plastic&logo=next.js&logoColor=white)
  ![TailwindCSS](https://img.shields.io/badge/tailwindcss-%2338B2AC.svg?style=plastic&logo=tailwind-css&logoColor=white)
  ![Cloudflare](https://img.shields.io/badge/Cloudflare-F38020?style=plastic&logo=Cloudflare&logoColor=white)
  ![Google Cloud](https://img.shields.io/badge/GoogleCloud-%234285F4.svg?style=plastic&logo=google-cloud&logoColor=white)
  ![Vercel](https://img.shields.io/badge/vercel-%23000000.svg?style=plastic&logo=vercel&logoColor=white)
  ![IntelliJ IDEA](https://img.shields.io/badge/IntelliJIDEA-000000.svg?style=plastic&logo=intellij-idea&logoColor=white)
  ![Obsidian](https://img.shields.io/badge/Obsidian-%23483699.svg?style=plastic&logo=obsidian&logoColor=white)
  ![PyCharm](https://img.shields.io/badge/pycharm-143?style=plastic&logo=pycharm&logoColor=black&color=black&labelColor=green)
  ![Vim](https://img.shields.io/badge/VIM-%2311AB00.svg?style=plastic&logo=vim&logoColor=white)
  ![Visual Studio Code](https://img.shields.io/badge/Visual%20Studio%20Code-0078d7.svg?style=plastic&logo=visual-studio-code&logoColor=white)
  ![WebStorm](https://img.shields.io/badge/webstorm-143?style=plastic&logo=webstorm&logoColor=white&color=black)
  ![Linux](https://img.shields.io/badge/Linux-FCC624?style=plastic&logo=linux&logoColor=black)
  ![macOS](https://img.shields.io/badge/mac%20os-000000?style=plastic&logo=macos&logoColor=F0F0F0)
  ![Ubuntu](https://img.shields.io/badge/Ubuntu-E95420?style=plastic&logo=ubuntu&logoColor=white)
  ![Swagger](https://img.shields.io/badge/-Swagger-%23Clojure?style=plastic&logo=swagger&logoColor=white)
  ![Terraform](https://img.shields.io/badge/terraform-%235835CC.svg?style=plastic&logo=terraform&logoColor=white)
  ![Ubiquiti](https://img.shields.io/badge/ubiquiti-%230559C9.svg?style=plastic&logo=ubiquiti&logoColor=white)
  ![Apache Flink](https://img.shields.io/badge/Apache%20Flink-E6526F?style=plastic&logo=Apache%20Flink&logoColor=white)
  ![Jenkins](https://img.shields.io/badge/jenkins-%232C5263.svg?style=plastic&logo=jenkins&logoColor=white)
  ![Bitbucket](https://img.shields.io/badge/bitbucket-%230047B3.svg?style=plastic&logo=bitbucket&logoColor=white)
  ![Git](https://img.shields.io/badge/git-%23F05033.svg?style=plastic&logo=git&logoColor=white)
  ![GitHub](https://img.shields.io/badge/github-%23121011.svg?style=plastic&logo=github&logoColor=white)
  
content:
  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Pega Systems
        link: pega.com
        # link_text: pega.com
        sub_title: Senior Principal Software Engineer
        caption: October 2020 - Present
        quote: >
            Pega Systems is a global leader in customer engagement and automation software. Its platform, including Customer Decision Hub and AI, enables real-time insights, personalized interactions, and streamlined workflows to enhance efficiency and engagement at scale.
        description: | # this will include new lines to allow paragraphs
            Driving the development of new features for Pega Customer Decision Hub, an AI-driven platform enabling businesses to deliver personalized, real-time customer interactions across diverse channels. Focused on enhancing database efficiency, improving processing performance, and reducing operational costs through innovative solutions.
            * Delivered the Decision Data Store API layer for enhanced schema management and efficient database access.
            * Optimized data flow execution, achieving a 25% reduction in per-record processing time.
            * Implemented Import Jobs enhancements, reducing query volume and improving overall processing time.
            * Developed the Cassandra provisioning service, streamlining database provisioning and enabling resource reuse, resulting in cost savings.

      - layout: left
        title: Sabre Holdings
        link: sabre.com
        # link_text: sabre.com
        sub_title: Team Lead Software Engineer
        caption: February 2016 - September 2020
        quote: >
            Sabre Corporation is a global leader in travel technology, offering high-performance Global Distribution Systems and software solutions for airlines, hotels, and travel agencies. Its tools streamline reservations, revenue management, and operations, powering millions of travel transactions worldwide.
        description: | # this will include new lines to allow paragraphs
            Led the development of new features for the Sabre High Performance Itinerary Selector back-end engine, ensuring compliance with industry standards such as ATPCO. 
            Focused on enhancing performance, optimizing resource utilization, and delivering market-specific solutions to maintain competitive advantage.
            * Delivered the Shortcut Pricing Multiple Itinerary Pricer, achieving a 20% reduction in CPU usage.
            * Implemented the Spanish Resident Fares discount mechanism, a critical feature for retaining Sabre’s presence in the Spanish market.

      - layout: left
        title: Nokia
        link: nokia.com
        # link_text: nokia.com
        sub_title: Senior Software Engineer
        caption: November 2010 - January 2016
        quote: >
            Nokia Networks is a global leader in telecommunications, specializing in LTE, LTE Advanced, and 5G technologies. The company delivers mobile and fixed network infrastructure, cloud solutions, and advanced connectivity tools, enabling high-speed, reliable, and secure networks.
        description: | # this will include new lines to allow paragraphs
            Software development for the LTE Control Plane (S1ap, X2ap, RRC) and Transport layers across multiple Flexi products and platforms, including Flexi Multiradio. 
            Focused on delivering innovative features, ensuring 3GPP compliance, and enhancing network performance. Contributed to groundbreaking solutions enabling market expansion and operational efficiency.
            * Delivered pre-3GPP Rel.12 Inter-eNodeB Carrier Aggregation, improving network interoperability and capacity.
            * Developed the first C-Plane performance measurement tests on Texas Instruments’ prototype board.
            * Implemented eNodeB commissioning over Bluetooth interface, simplifying the setup process.
            * Delivered Earthquake Tsunami Warning System (ETWS) and Commercial Mobile Alert System (CMAS), critical for Asian market entry.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wroclaw University of Science and Technology
        caption: 2005 - 2011
        sub_title: |
            Electronics Engineering, MSc Eng
        quote: >
            Wroclaw University of Science and Technology is a leading Polish technical university, known for its research excellence and strong industry partnerships. It offers engineering and technology programs, preparing graduates to tackle global challenges through innovation and collaboration.
        description: | # this will include new lines to allow paragraphs
            Academic coursework encompassed a broad range of foundational and advanced topics, including Analog and Digital Circuit Design, PCB Design, and Signal Processing. The focus extended to Embedded Systems, Programming in C/C++ and Java, SQL for database management, and advanced modeling techniques using MATLAB. Additional expertise was gained in FPGA design, Microcontroller programming, Electronics Metrology, LabView Visual Programming, and Sensor Technology, offering a comprehensive skill set in hardware and software integration.

  - title: Other
    layout: text
    content: | # this will include new lines to allow paragraphs
        Outside of software engineering, I enjoy tennis, cycling, and engaging in strategic hobbies like trading card games and board games.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-pdf
