# Site
repository: jakub-k-slys/jakub
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jakub Slys
title: Senior Principal Software Engineer
email: jakub@slys.dev
website: iam.slys.dev

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: jakub-k-slys
#github_username:  jakub-k-slys
#instagram_username: jakub.k.slys
linkedin_username: jakub-k-slys

# Additional icon links
additional_links:
- title: iam.slys.dev
  icon: fas fa-globe
  url: iam.slys.dev

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  A highly skilled software engineer with extensive experience in high-performance systems and big data. 
  Expertise includes programming languages such as <mark>C++</mark>, <mark>JAVA</mark>, and <mark>Python</mark>. 
  A strong emphasis is placed on clean and maintainable code, leveraging <mark>Test-Driven Development (TDD)</mark>, <mark>Behavior-Driven Development (BDD)</mark>, and <mark>Domain-Driven Design (DDD)</mark> to create robust and scalable solutions. 
  Work often involves designing and implementing systems capable of processing large-scale data and delivering exceptional performance under heavy loads.  

  Dedicated to continuous learning and the exploration of new tools and methodologies to push the boundaries of software engineering.
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Pega Systems
        link: pega.com
        # link_text: pega.com
        sub_title: Senior Principal Software Engineer
        caption: April 2022 - Present
        quote: >
            Pega Systems is a global leader in customer engagement and automation software. Its platform, including Customer Decision Hubs (CDH) and AI, enables real-time insights, personalized interactions, and streamlined workflows to enhance efficiency and engagement at scale.
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: left
        sub_title: Principal Software Engineer
        caption: October 2020 - March 2022
      - layout: left
        title: Sabre Holdings
        link: sabre.com
        # link_text: sabre.com
        sub_title: Team Lead Software Engineer
        caption: February 2016 - September 2020
        quote: >
            Sabre Corporation is a global leader in travel technology, offering high-performance Global Distribution Systems (GDS) and software solutions for airlines, hotels, and travel agencies. Its tools streamline reservations, revenue management, and operations, powering millions of travel transactions worldwide.
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: left
        title: Nokia
        link: nokia.com
        # link_text: nokia.com
        sub_title: Senior Software Engineer
        caption: November 2010 - January 2016
        quote: >
            Nokia Networks, a division of Nokia Corporation, is a global leader in telecommunications, specializing in LTE, LTE Advanced, and 5G technologies. The company delivers mobile and fixed network infrastructure, cloud solutions, and advanced connectivity tools, enabling high-speed, reliable, and secure networks.
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wroclaw University of Science and Technology
        caption: 2005 - 2011
        sub_title: Electronics Engineering, MSc Eng
        quote: >
            Wroclaw University of Science and Technology is a leading Polish technical university, known for its research excellence and strong industry partnerships. It offers engineering and technology programs, preparing graduates to tackle global challenges through innovation and collaboration.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-pdf
